### ISSUE TITLE
e2e test return with no project error

### ISSUE THREAD

**Issue by link89** [typescript-language-server/typescript-language-server#256]
I just try to use this project with vscode-jsonrpc to parse ts file and the below is my experiment code:
```typescript
import test from 'ava';
import { expect } from "chai";

import * as cp from 'child_process';
import * as lsp from 'vscode-languageserver-protocol/node'

test('test vscode-jsonrpc', async t => {
  const childProcess = cp.spawn('typescript-language-server', ['--stdio'])
  try {
    const connection = lsp.createMessageConnection(
      new lsp.StreamMessageReader(childProcess.stdout),
      new lsp.StreamMessageWriter(childProcess.stdin)
    );

    const testFileUri = `file://${__dirname}/tests-data/example.ts`;
    const workspaceUri = `file://${__dirname}/tests-data`;

    connection.listen();

    let res;

    const initRequest: lsp.InitializeParams = {
			rootUri: workspaceUri,
			processId: 1,
			capabilities: {},
			workspaceFolders: [
        {uri: workspaceUri, name: 'example'}
      ]
		};
    res = await connection.sendRequest(lsp.InitializeRequest.type, initRequest);
    console.log(JSON.stringify(res, null, 2));
    connection.sendNotification(lsp.InitializedNotification.type, {});

    const documentSymbolRequest: lsp.DocumentSymbolParams = {
			textDocument: lsp.TextDocumentIdentifier.create(testFileUri),
		};
    res = await connection.sendRequest(lsp.DocumentSymbolRequest.type, documentSymbolRequest);
    console.log(JSON.stringify(res, null, 2));

  } finally {
    childProcess.kill();
  }
});
```

I just follow the LSP spec to send initialize request  before DocumentSymbolRequests.type, but it fails with the error `No Project`. I have dump the tss log and I don't know what's wrong with with it.
```
Info 0    [11:26:12.803] Starting TS Server
Info 1    [11:26:12.805] Version: 4.4.2
Info 2    [11:26:12.805] Arguments: /Users/anyuser/.nvm/versions/node/v12.0.0/bin/node /Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js --cancellationPipeName /private/var/folders/0d/68zzhkx52vl9hs7z96pcllk00000gn/T/4796c54d0df7dfb01f9bcf8909dca90b/tscancellation*
Info 3    [11:26:12.805] Platform: darwin NodeVersion: 12 CaseSensitive: true
Info 4    [11:26:12.805] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [11:26:12.815] Binding...
Info 6    [11:26:12.824] request:
    {"command":"configure","seq":1,"type":"request","arguments":{"preferences":{"allowTextChangesInNewFiles":true,"includeCompletionsForModuleExports":true,"includeCompletionsWithInsertText":true}}}
Info 7    [11:26:12.825] response:
    {"seq":0,"type":"response","command":"configure","request_seq":1,"success":true}
Perf 8    [11:26:12.826] 1::configure: async elapsed time (in milliseconds) 1.7322
Info 9    [11:26:12.826] request:
    {"command":"compilerOptionsForInferredProjects","seq":2,"type":"request","arguments":{"options":{"module":"CommonJS","target":"ES2016","jsx":"Preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Perf 10   [11:26:12.827] 2::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.6796
Info 11   [11:26:12.827] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":2,"success":true,"body":true}
Info 12   [11:26:12.827] request:
    {"command":"navtree","seq":3,"type":"request","arguments":{"file":"/Users/anyuser/workspace/my-app/lsp-playground/tests-data/example.ts"}}
Err 13    [11:26:12.843] Could not find file "/Users/anyuser/workspace/my-app/lsp-playground/tests-data/example.ts".
All files are: []
Err 14    [11:26:12.844] Exception on executing command {"command":"navtree","seq":3,"type":"request","arguments":{"file":"/Users/anyuser/workspace/my-app/lsp-playground/tests-data/example.ts"}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:159721:23)
        at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168052:42)
        at IOSession.Session.getNavigationTree (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168408:31)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:167169:61)
        at /Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168873:88
        at IOSession.Session.executeWithRequestId (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168864:28)
        at IOSession.Session.executeCommand (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168873:33)
        at IOSession.Session.onMessage (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:168899:35)
        at Interface.<anonymous> (/Users/anyuser/workspace/my-app/node_modules/typescript/lib/tsserver.js:171504:31)
        at Interface.emit (events.js:196:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:196:13)
        at addChunk (_stream_readable.js:290:12)
```

The file do exist, but it just said `All files are: []`. I don't know if there is any missing steps.

**Comment by NicholasLYang** [comment]
@link89, I'm running into almost this exact same issue. Did you ever solve it?

**Comment by rchl** [comment]
You need to at least send the `didOpen` notification first.

**Comment by link89** [comment]
Hi @NicholasLYang @rchl gives the right answer, `didOpen` is missing.  Before sending `documentSymbolRequest` you need to read file and send `didOpen` request like below.

```typescript
    const text = fs.readFileSync(SAMPLE_TS_FILE, { encoding: 'utf-8' });
    const didOpenRequest: lsp.DidOpenTextDocumentParams = {
      textDocument: {
        uri: testFileUri,
        languageId: 'typescript',
        version: 1,
        text,
      }
    }
    connection.sendNotification(lsp.DidOpenTextDocumentNotification.type, didOpenRequest);
```
