### ISSUE TITLE
typescript-language-server process crash after initialized

### ISSUE THREAD

**Issue by link89** [typescript-language-server/typescript-language-server#262]
I am trying to use `typescript-language-server` to extract symbols from ts file via `vscode-languageserver-protocol`, and what make me confuse is the language server may exist without any log. Here is the minimal reproducing steps I have found.

1. prepare test environment
`mkdir lsp-demo && cd lsp-demo && npm init`
`npm install vscode-languageserver-protocol  typescript ts-node @type/node`
`npm install -g typescript typescript-language-server`

2. create the test file `lsp-demo.ts`, this script will parse itself and print its symbols.
```typescript
import * as cp from 'child_process';
import * as fs from 'fs';
import { pathToFileURL } from 'url';
import * as lsp from 'vscode-languageserver-protocol/node';

const WORKSPACE_URI = pathToFileURL(__dirname).toString();
const TEST_FILE = __filename;
const TEST_FILE_URI = pathToFileURL(TEST_FILE).toString();

(async () => {

  const childProcess = cp.spawn('typescript-language-server', ['--stdio'])
  try {
    // Use stdin and stdout for communication:
    const connection = lsp.createMessageConnection(
      new lsp.StreamMessageReader(childProcess.stdout),
      new lsp.StreamMessageWriter(childProcess.stdin)
    );
    connection.listen();

    // init
    const initRequest: lsp.InitializeParams = {
      rootUri: WORKSPACE_URI,
      processId: 1,
      capabilities: {},
      workspaceFolders: null,
    };
    const r = await connection.sendRequest(lsp.InitializeRequest.type, initRequest);
    connection.sendNotification(lsp.InitializedNotification.type, {});

    // !!!
    // it will fails if you uncomment the following line
    // await new Promise(resolve => setTimeout(resolve, 5e3));

    const text = fs.readFileSync(TEST_FILE, { encoding: 'utf-8' });
    // open file
    const didOpenRequest: lsp.DidOpenTextDocumentParams = {
      textDocument: {
        uri: TEST_FILE_URI,
        languageId: 'typescript',
        version: 1,
        text,
      }
    }
    connection.sendNotification(lsp.DidOpenTextDocumentNotification.type, didOpenRequest);

    // get all symbols
    const documentSymbolRequest: lsp.DocumentSymbolParams = {
      textDocument: lsp.TextDocumentIdentifier.create(TEST_FILE_URI),
    }
    const res = await connection.sendRequest(lsp.DocumentSymbolRequest.type, documentSymbolRequest);
    console.log(res);
  } finally {
    childProcess.kill();
  }
})().catch(console.error)
```
And run the script with `npx ts-node lsp-demo.ts`
The script will work as expect. 
But if you uncomment the 5s delay in the test script, you will see this error
```
ConnectionError: Connection is closed.
    at throwIfClosedOrDisposed (/private/tmp/lsp-demo/node_modules/vscode-jsonrpc/lib/common/connection.js:723:19)
    at Object.sendNotification (/private/tmp/lsp-demo/node_modules/vscode-jsonrpc/lib/common/connection.js:805:13)
    at /private/tmp/lsp-demo/lsp-demo.ts:43:16 {
  code: 1
}
```
tsserver.log
```
Info 0    [13:59:13.517] Starting TS Server
Info 1    [13:59:13.518] Version: 4.4.3
Info 2    [13:59:13.518] Arguments: /Users/henry.xu/.nvm/versions/node/v12.0.0/bin/node /private/tmp/lsp-demo/node_modules/typescript/lib/tsserver.js --cancellationPipeName=/private/var/folders/0d/68zzhkx52vl9hs7z96pcllk00000gn/T/eb3d504d03dee4dc81637fa87789c7cb/tscancellation*
Info 3    [13:59:13.518] Platform: darwin NodeVersion: 12 CaseSensitive: true
Info 4    [13:59:13.518] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [13:59:13.527] Binding...
Info 6    [13:59:13.534] request:
    {"command":"configure","seq":1,"type":"request","arguments":{"preferences":{"allowTextChangesInNewFiles":true,"includeCompletionsForModuleExports":true,"includeCompletionsWithInsertText":true}}}
Info 7    [13:59:13.535] response:
    {"seq":0,"type":"response","command":"configure","request_seq":1,"success":true}
Perf 8    [13:59:13.536] 1::configure: async elapsed time (in milliseconds) 1.5164
Info 9    [13:59:13.536] request:
    {"command":"compilerOptionsForInferredProjects","seq":2,"type":"request","arguments":{"options":{"module":"CommonJS","target":"ES2016","jsx":"Preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Perf 10   [13:59:13.536] 2::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.5324
Info 11   [13:59:13.536] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":2,"success":true,"body":true}
Info 12   [13:59:13.537] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":48816}}
```
Not very useful message.

The 5s delay is wait for the language server to crash, if you are luck enough to send request before it crash, it will work as expect, otherwise it will fail. I am new to LSP and I believe there may have some mistake in the initialize option lead to this mistake but I cannot figure it out by myself.

**Comment by rchl** [comment]
Set the `processId` to `null`.
The library sets up a parent process watcher at https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/server/src/node/main.ts#L79-L93. If it can't find that parent process, it will kill the server within 3 seconds. Since you are passing non-existent ID, it is being killed.

**Comment by link89** [comment]
Thank you @rchl . You have saved my day. I just copy the snippet from some test suite and didn't aware that it's just a placeholder because it works well before.
