### ISSUE TITLE
tsserver fails to start in neovim 

### ISSUE THREAD

**Issue by phileagleson** [typescript-language-server/typescript-language-server#263]
When starting from neovim using lsp-config, I get error:
Client 1 quit with exit code 1 and signal 0

logs show:

.../vim/lsp/rpc.lua:462    "rpc"   "typescript-language-server"    "stderr"        "undefined:1\n<--- Last few GCs --->\n^\n\nSyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at TspClient.processMessage (/usr/local/lib/node_modules/typescript-language-server/lib/tsp-client.js:135:30)\n    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript-language-server/lib/tsp-client.js:85:56)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:329:10)\n    at Interface._normalWrite (readline.js:474:12)\n    at Socket.ondata (readline.js:186:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n"

**Comment by rchl** [comment]
Try to start the server with logging enabled and see if the log file has any more details.

You have to start the server process with those arguments: `--tsserver-log-file=ts-logs.txt --log-level=4`

**Comment by phileagleson** [comment]
I just get an empty log.
I forgot to mention,  I'm on MacOs 11.5.2, node version 12.18.4, npm version 7.24.0, and nvim version 0.5.1

**Comment by phileagleson** [comment]
I updated to version 16 of node and I or get more info. Still not sure where the problem is though. For reference, I have 2 ts file a foo and bar with a package json

foo.ts
`export default function foo(a: number): number {`
        `return a + 1`
`}`


bar.ts
`import foo from './foo'`
 `foo()`



`-32603: Request textDocument/definition failed with message: Error processing request. Cannot read properties of undefined (reading 'getSourceFiles')
TypeError: Cannot read properties of undefined (reading 'getSourceFiles')
    at ConfiguredProject.Project.getScriptInfos (/usr/local/lib/node_modules/typescript/lib/tsserver.js:161488:44)
    at ProjectService.sendProjectTelemetry (/usr/local/lib/node_modules/typescript/lib/tsserver.js:164294:66)
    at ConfiguredProject.updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:162648:37)
    at updateProjectIfDirty (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163133:45)
    at updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163567:34)
    at Map.forEach (<anonymous>)
    at ProjectService.ensureProjectStructuresUptoDate (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163570:41)
    at ProjectService.doEnsureDefaultProjectForFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163548:22)
    at ProjectService.ensureDefaultProjectForFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163545:75)
    at IOSession.Session.getFileAndProjectWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168068:87)
    at IOSession.Session.getFileAndProject (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168051:29)
    at IOSession.Session.getDefinition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:167716:31)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:166980:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (node:events:390:28)
    at Interface._onLine (node:readline:487:10)
    at Interface._normalWrite (node:readline:661:12)
    at Socket.ondata (node:readline:269:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
`

`-32603: Request textDocument/definition failed with message: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/usr/local/lib/node_modules/typescript/lib/tsserver.js:159728:23)
    at ScriptInfo.getDefaultProject (/usr/local/lib/node_modules/typescript/lib/tsserver.js:160575:46)
    at ProjectService.doEnsureDefaultProjectForFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163550:48)
    at ProjectService.ensureDefaultProjectForFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163545:75)
    at IOSession.Session.getFileAndProjectWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168068:87)
    at IOSession.Session.getFileAndProject (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168051:29)
    at IOSession.Session.getDefinition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:167716:31)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:166980:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (node:events:390:28)
    at Interface._onLine (node:readline:487:10)
    at Interface._normalWrite (node:readline:661:12)
    at Socket.ondata (node:readline:269:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
-32603: Request textDocument/definition failed with message: Error processing request. No Project.
`

**Comment by phileagleson** [comment]
Found the issue here https://stackoverflow.com/questions/39751420/tsserver-error-processing-request-no-project

I had a similar issue, I had a tsconfig.json file higher up in my src tree.
