### ISSUE TITLE
Auto import not working when having multiple source

### ISSUE THREAD

**Issue by princemaple** [typescript-language-server/typescript-language-server#312]
Hi,

Thanks heaps for adding annotations and closing #280 

One thing that changed after the recent update is, when triggering auto import (by pressing tab for auto completion) on something that has multiple import sources, the auto import doesn't seem to work.

Some examples:

1. In my own code, I have a file with all the types and a file with all my api clients. The file with api clients uses and re-exports the types. It used to auto import the types without problems but now fails.
2. In rxjs 7+, operators are exposed from both `rxjs/operators` and `rxjs` root. The recent updated is starting to have trouble importing the operators.

Thanks for the great work.

EDIT - To clarify: explicit code action of auto import works.

**Comment by rchl** [comment]
If need some way of reproducing to look into it.

Or otherwise at least server communication logs. Are you using ST?

**Comment by princemaple** [comment]
https://gist.github.com/princemaple/4d38921171de526a717508c5863731d9

(⬆️long, my project code)

There seems to be one more prerequisite. One of the import source is already in the file.

(⬇️short, repro)

Given:
```ts
import {switchMap} from 'rxjs/operators';

switchMap;

groupBy|<-
```

Auto complete on `groupBy` fails. `groupBy` can come from either `rxjs` or `rxjs/operators`


```
:: --> LSP-typescript textDocument/codeAction(3179): {'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/x.ts'}, 'context': {'diagnostics': [{'source': 'typescript', 'code': 2304, 'severity': 1, 'tags': [], 'message': "Cannot find name 'groupby'.", 'range': {'end': {'character': 7, 'line': 5}, 'start': {'character': 0, 'line': 5}}}]}, 'range': {'end': {'character': 7, 'line': 5}, 'start': {'character': 0, 'line': 5}}}
:: <-  LSP-typescript textDocument/publishDiagnostics: {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/contract-table.component.ts', 'diagnostics': [{'source': 'typescript', 'code': 2304, 'severity': 1, 'tags': [], 'message': "Cannot find name 'groupBy'.", 'range': {'end': {'character': 15, 'line': 113}, 'start': {'character': 8, 'line': 113}}}]}
:: --> LSP-typescript textDocument/codeAction(3180): {'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/contract-table.component.ts'}, 'context': {'diagnostics': [{'source': 'typescript', 'code': 2304, 'severity': 1, 'tags': [], 'message': "Cannot find name 'groupBy'.", 'range': {'end': {'character': 15, 'line': 113}, 'start': {'character': 8, 'line': 113}}}]}, 'range': {'end': {'character': 15, 'line': 113}, 'start': {'character': 8, 'line': 113}}}
:: <<< LSP-typescript 3179: [{'command': {'arguments': [{'endOffset': 8, 'startLine': 6, 'action': 'Move to a new file', 'refactor': 'Move to a new file', 'file': 'c:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/x.ts', 'startOffset': 1, 'endLine': 6}], 'command': '_typescript.applyRefactoring', 'title': 'Move to a new file'}, 'title': 'Move to a new file', 'kind': 'refactor.move'}]
:: <<< LSP-typescript 3180: [{'command': {'arguments': [{'documentChanges': [{'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/contract-table.component.ts', 'version': 1096}, 'edits': [{'newText': 'groupBy, ', 'range': {'end': {'character': 8, 'line': 7}, 'start': {'character': 8, 'line': 7}}}]}]}], 'command': '_typescript.applyWorkspaceEdit', 'title': 'Add \'groupBy\' to existing import declaration from "lodash-es"'}, 'title': 'Add \'groupBy\' to existing import declaration from "lodash-es"', 'kind': 'quickfix'}, {'command': {'arguments': [{'documentChanges': [{'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/contract-table.component.ts', 'version': 1096}, 'edits': [{'newText': 'groupBy, ', 'range': {'end': {'character': 16, 'line': 6}, 'start': {'character': 16, 'line': 6}}}]}]}], 'command': '_typescript.applyWorkspaceEdit', 'title': 'Add \'groupBy\' to existing import declaration from "rxjs/operators"'}, 'title': 'Add \'groupBy\' to existing import declaration from "rxjs/operators"', 'kind': 'quickfix'}]
:: <-  LSP-typescript textDocument/publishDiagnostics: {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/shared/backend/resource-cache.ts', 'diagnostics': []}
:: --> LSP-typescript textDocument/codeAction(3181): {'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/shared/backend/resource-cache.ts'}, 'context': {'diagnostics': []}, 'range': {'end': {'character': 0, 'line': 0}, 'start': {'character': 0, 'line': 0}}}
:: <<< LSP-typescript 3181: []
:: --> LSP-typescript completionItem/resolve(3182): {'detail': 'rxjs', 'sortText': '\uffff16', 'kind': 6, 'commitCharacters': ['.', ',', '('], 'label': 'groupBy', 'data': {'line': 6, 'file': 'c:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/x.ts', 'offset': 6, 'entryNames': [{'name': 'groupBy', 'source': 'rxjs', 'data': {'fileName': 'c:/Users/chenp/code/songri-desk-frontend/node_modules/rxjs/dist/types/index.d.ts', 'exportName': 'groupBy', 'moduleSpecifier': 'rxjs'}}]}}
:: <~~ LSP-typescript 3182: {'message': 'Request completionItem/resolve failed with message: Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at getCompletionEntryCodeActionsAndSourceDisplay (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:126516:22)\n    at Object.getCompletionEntryDetails (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:126472:30)\n    at Object.getCompletionEntryDetails (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:156798:35)\n    at c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168262:57\n    at Object.mapDefined (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:616:30)\n    at IOSession.Session.getCompletionEntryDetails (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168260:33)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:167087:61)\n    at c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168880:88\n    at IOSession.Session.executeWithRequestId (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168871:28)\n    at IOSession.Session.executeCommand (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168880:33)\n    at IOSession.Session.onMessage (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:168906:35)\n    at Interface.<anonymous> (c:\\Users\\chenp\\code\\songri-desk-frontend\\node_modules\\typescript\\lib\\tsserver.js:171511:31)\n    at Interface.emit (node:events:390:28)\n    at Interface._onLine (node:readline:487:10)\n    at Interface._normalWrite (node:readline:661:12)\n    at Socket.ondata (node:readline:269:10)\n    at Socket.emit (node:events:390:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)', 'code': -32603}
::  -> LSP-typescript textDocument/didChange: {'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/x.ts', 'version': 290}, 'contentChanges': [{'text': '', 'rangeLength': 7, 'range': {'end': {'character': 7, 'line': 5}, 'start': {'character': 0, 'line': 5}}}, {'text': 'groupBy', 'rangeLength': 0, 'range': {'end': {'character': 0, 'line': 5}, 'start': {'character': 0, 'line': 5}}}]}
:: --> LSP-typescript typescript/inlayHints(3183): {'textDocument': {'uri': 'file:///C:/Users/chenp/code/songri-desk-frontend/projects/purchase/src/app/contract-table/x.ts'}}
:: <<< LSP-typescript 3183: {'inlayHints': []}
```

**Comment by princemaple** [comment]
However, this works:

```
import { Subject } from 'rxjs';

Subject

groupBy|<-
```

```ts
import { groupBy, Subject } from 'rxjs';
// ------^^^^^^^ gives me that

Subject

groupBy
```

**Comment by rchl** [comment]
Which typescript version is that?

The `completion/resolve` request fails in typescript with:

```
Request completionItem/resolve failed with message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getCompletionEntryCodeActionsAndSourceDisplay (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:126516:22)
    at Object.getCompletionEntryDetails (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:126472:30)
    at Object.getCompletionEntryDetails (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:156798:35)
    at c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168262:57
    at Object.mapDefined (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:616:30)
    at IOSession.Session.getCompletionEntryDetails (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168260:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:167087:61)
    at c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168871:28)
    at IOSession.Session.executeCommand (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168880:33)
    at IOSession.Session.onMessage (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:168906:35)
    at Interface.<anonymous> (c:\Users\chenp\code\songri-desk-frontend\node_modules\typescript\lib\tsserver.js:171511:31)
    at Interface.emit (node:events:390:28)
    at Interface._onLine (node:readline:487:10)
    at Interface._normalWrite (node:readline:661:12)
    at Socket.ondata (node:readline:269:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I would be surprised if that's due to something wrong on our side.

**Comment by rchl** [comment]
Actually I can reproduce but this also reproduces in older versions of `typescript-language-server` and even in VSCode.

So the best course of action would be to report that issues in the typescript repo against VSCode (if you report against this server then it will most likely be ignored).

**Comment by princemaple** [comment]
I'm on typescript 4.4. Both global ts and in-project ts.

Interesting. I was 90% sure this only happened after the recent update, as I've been using the same setup for a long time. Anyway, thanks for investigating!

**Comment by rchl** [comment]
Note that we could handle the error and, even if not make the auto-import work then at least make the completion insert `groupBy`. But that would sort of hide the real issue.

**Comment by princemaple** [comment]
I think the completion works either way? (just tested, completion works)
Only the auto-import part is buggy.

**Comment by rchl** [comment]
Actually it maybe has broken lately when we've aligned default typescript settings with vscode. I can try later to test without new options.

Though reverting the options will disable some functionality (possibly the import annotations) so proper solution would still be to fix the root issue.

**Comment by rchl** [comment]
Yes. Disabling `allowIncompleteCompletions` makes it work (though you don't get annotations then).

```
    "initializationOptions": {
        "preferences": {
            "allowIncompleteCompletions": false,
        },
    },
```

**Comment by princemaple** [comment]
Thanks for getting to the bottom of this!

**Comment by predragnikolic** [comment]
I found out that `allowIncompleteCompletions` has also some other "negative" effects on auto import worth knowing.

I have a react project, 
and when I try to import `useEffect` for the first time,
I expect to get a line like this:
```
import {useEffect} from "react";
```
but instead I got an auto import like this:
```
import { useEffect } from "hoist-non-react-statics/node_modules/@types/react"
```

And because I do not see what gets auto imported, as soon as I press save, my build script stops, so I had to manually remove that line to `import {useEffect} from "react";` and start the build script again(with `yarn start`) 

Until I figured out the cause... `allowIncompleteCompletions` :)

**Comment by rchl** [comment]
I wonder if the tsserver is potentially relying on the `completion/resolve` request to "fixup" things but in ST that is not done before completing completions. Would be good to see logs.

**Comment by predragnikolic** [comment]
in ST additionalTextEdits are applied only after resolving the completion item. 

That would mean that that the server should resolve the path correctly, but that is not the case.

FWIW, I also managed to reproduce the issue with VS Code as well, and that made me think that the issue lies maybe in tsserver itself.

https://user-images.githubusercontent.com/22029477/143656562-020d0e33-0578-4523-8386-055f52166698.mp4


https://user-images.githubusercontent.com/22029477/143656555-900cc74d-8b41-4b13-96f6-8af580040e88.mp4

**Comment by rchl** [comment]
> And because I do not see what gets auto imported, as soon as I press save,

From your later videos it appears that you can actually see what's being imported before it imports.
