### ISSUE TITLE
No such built-in module: node:fs/promises

### ISSUE THREAD

**Issue by jakescript** [typescript-language-server/typescript-language-server#572]
trying to start the language server to use with the nvim lsp config, noticed it wasnt starting to I tried to manually start with 
typescript-language-server --stdio

it throws this error
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:fs/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:281:11)
    at new ModuleJob (internal/modules/esm/module_job.js:37:41)
    at Loader.getModuleJob (internal/modules/esm/loader.js:277:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:49:17)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:53:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

currently on node: v12.22.11

**Comment by ddaniel27** [comment]
I have the same issue last night. I had to install `npm i -g typescript-language-server@1.0.0` and everything works fine. I don't know what happened in last commit.

**Comment by jakescript** [comment]
still the same issue

**Comment by ddaniel27** [comment]
Did you try to uninstall all `typescript-language-server` installations first?
See what happen when you use `npm ls -g` if the tls version is 1.0.0 or 1.1.0

If you have tls@1.1.0 in global packages try to do:

- `npm uninstall -g typescript-language-server` to uninstall tls@1.1.0 bc npm doesn't replace the package when you install an older version.
- `npm install -g typescript-language-server@1.0.0` to install tls@1.0.0

That was my way to install tls@1.0.0 in an EC2 last night. I hope this can help you.

**Comment by jakescript** [comment]
Yeah I made sure to uninstall, try running the command again and make sure it wasn't recognized to ensure it was uninstalled. Then reinstalled version 1.0.0 and then ran the command and got the same issue

**Comment by predragnikolic** [comment]
Your node version is 12.
The minimum required node version is 14.

https://github.com/typescript-language-server/typescript-language-server/releases/tag/v1.0.0
> LSP libraries updated to match the 3.17 version of the LSP spec. Requires minimum Node 14.

**Comment by rchl** [comment]
You'd have to stick to version below 1.0.0 if you want it to work with Node 12.

**Comment by DonnieWest** [comment]
FWIW Neovim just uses whatever is on your $PATH (see https://github.com/neovim/nvim-lspconfig/blob/a0ba718470786370d7eca4ca762e9ed68a21b8bd/lua/lspconfig/server_configurations/tsserver.lua#L3 )

Additionally, Neovim's `nvim-lspconfig` project is just a loose set of configurations that you can override. Either provide a `cmd` property that suits your need or use [project local settings](https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings) to override on a per-project basis
