### ISSUE TITLE
ResponseError: Unhandled method window/workDoneProgress/create

### ISSUE THREAD

**Issue by Himenon** [typescript-language-server/typescript-language-server#845]
Hello.

When connecting monaco-languageclient to typescript-language-server, an error occurs in the LSP and it shuts down.

I am looking for a way to avoid this problem.

Using:

* `node -v`: v18.19.0
* typescript-language-server@4.2.0
* monaco-languageclient@7.3.0
  * vscode-languageclient@9.0.1
  * vscode-languageserver-protocol@3.17.5

LSP startup commands

```bash
typescript-language-server --studio
```

The following sample was rewritten for typescript-language-server and verified.

* https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/src/python

## Log Message

```
file:///Users/himenon/Desktop/monaco-editor-playground/node_modules/.pnpm/typescript-language-server@4.2.0/node_modules/typescript-language-server/lib/cli.mjs:4012
                responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                       ^

ResponseError: Unhandled method window/workDoneProgress/create
    at handleResponse (file:///Users/himenon/Desktop/monaco-editor-playground/node_modules/.pnpm/typescript-language-server@4.2.0/node_modules/typescript-language-server/lib/cli.mjs:4012:40)
    at handleMessage (file:///Users/himenon/Desktop/monaco-editor-playground/node_modules/.pnpm/typescript-language-server@4.2.0/node_modules/typescript-language-server/lib/cli.mjs:3823:11)
    at processMessageQueue (file:///Users/himenon/Desktop/monaco-editor-playground/node_modules/.pnpm/typescript-language-server@4.2.0/node_modules/typescript-language-server/lib/cli.mjs:3838:13)
    at Immediate.<anonymous> (file:///Users/himenon/Desktop/monaco-editor-playground/node_modules/.pnpm/typescript-language-server@4.2.0/node_modules/typescript-language-server/lib/cli.mjs:3814:11)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32601,
  data: undefined
}
```

## Related Issue

* https://github.com/TypeFox/monaco-languageclient/issues/586
* https://github.com/TypeFox/monaco-languageclient/discussions/542

**Comment by Himenon** [comment]
Thanks for the quick Bug Fix!

Looking forward to the release.
