### ISSUE TITLE
Typescript Server Error when `includeInlayVariableTypeHints = true` and an arrow function is made.

### ISSUE THREAD

**Issue by eksno** [typescript-language-server/typescript-language-server#889]
I get a Typescript Server Error when I enable `includeInlayVariableTypeHints = true` and use an arrow function.

Here is the error:

```error
tsserver: 1: <semantic> TypeScript Server Error (5.3.3)
Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
Error: Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
    at visitForDisplayParts (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165383:17)
    at visitForDisplayParts (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165188:11)
    at /home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165391:9
    at Array.forEach (<anonymous>)
    at visitDisplayPartList (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165387:13)
    at visitForDisplayParts (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165340:11)
    at typeToInlayHintParts (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:165113:5)
    at visitVariableLikeDeclaration (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164921:23)
    at visitor (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164843:7)
    at visitNodes (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30235:22)
    at forEachChildInVariableDeclarationList (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30454:12)
    at forEachChild (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30744:35)
    at visitor (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164858:12)
    at visitNode2 (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30227:18)
    at forEachChildInVariableStatement (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30451:59)
    at forEachChild (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30744:35)
    at visitor (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164858:12)
    at visitNodes (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30235:22)
    at forEachChildInSourceFile (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30448:12)
    at forEachChild (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:30744:35)
    at visitor (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164858:12)
    at Object.provideInlayHints (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:164819:3)
    at Object.provideInlayHints2 [as provideInlayHints] (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:145844:34)
    at ls.provideInlayHints (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript-svelte-plugin@0.3.37_svelte@4.2.12_typescript@5.3.3/node_modules/typescript-svelte-plugin/dist/src/language-service/inlay-hints.js:14:14)
    at IpcIOSession.provideInlayHints (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:184197:48)
    at provideInlayHints (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:183356:43)
    at /home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185375:69
    at IpcIOSession.executeWithRequestId (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185367:14)
    at IpcIOSession.executeCommand (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185375:29)
    at IpcIOSession.onMessage (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:185417:51)
    at process.<anonymous> (/home/eksno/vcs/futino/aitino/apps/web/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/tsserver.js:186999:14)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

How to reproduce:

1. Enable inlay-hints
2. Set `includeInlayVariableTypeHints = true` in your lspconfig for tserver
3. Open a ts file with an arrow function.

I would guess this is happening because it thinks you are declaring a variable and thus tries to use the same algorithm it would for any other variable declaration to determine and inlay the type. But of course this errors.

I've disabled the setting for now but I find variable type hints really useful so I'd like some help on how to sort this out.

**Comment by rchl** [comment]
This likely also reproduces in VSCode and should be reported in the [Typescript repo](https://github.com/microsoft/TypeScript).
