### ISSUE TITLE
Hovers are always empty if didOpen was not sent for the document

### ISSUE THREAD

**Issue by felixfbecker** [typescript-language-server/typescript-language-server#89]
Hi, I'm trying the language server out but I always get back empty hovers.
I'm spawning it with `vscode-ws-jsonrpc`:
```ts
const languageServerConnection = rpcServer.createServerProcess('TypeScript language', 'node', [
        path.resolve(__dirname, '..', '..', 'node_modules', 'typescript-language-server', 'lib', 'cli.js'),
        '--stdio',
        '--tsserver-path=' + path.join(__dirname, '..', '..', 'node_modules', 'typescript', 'bin', 'tsserver'),
        '--log-level=4',
    ])
```
using latest `typescript-language-server@0.3.6` and `typescript@3.1.4`.

Here are the logs:
```
TypeScript server: [lspserver] initialize {
  "processId": 0,
  "rootUri": "file:///var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo",
  "workspaceFolders": [
    {
      "name": "",
      "uri": "file:///var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo"
    }
  ],
  "capabilities": {},
  "rootPath": "/var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo"
}
extension.ts:67 TypeScript server: [tsclient] Starting tsserver : '/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/bin/tsserver --cancellationPipeName /private/var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/94fcf775f43fb917bebc426239655113/tscancellation*'
extension.ts:71 TypeScript server: [tsclient] request {
  "command": "configure",
  "seq": 1,
  "type": "request",
  "arguments": {
    "preferences": {
      "allowTextChangesInNewFiles": true
    }
  }
}
extension.ts:71 TypeScript server: [lspserver] onInitialize result {
  "capabilities": {
    "textDocumentSync": 2,
    "completionProvider": {
      "triggerCharacters": [
        ".",
        "\"",
        "'",
        "/",
        "@",
        "<"
      ],
      "resolveProvider": true
    },
    "codeActionProvider": true,
    "definitionProvider": true,
    "documentFormattingProvider": true,
    "documentHighlightProvider": true,
    "documentSymbolProvider": true,
    "executeCommandProvider": {
      "commands": [
        "_typescript.applyWorkspaceEdit",
        "_typescript.applyCodeAction",
        "_typescript.applyRefactoring",
        "_typescript.organizeImports",
        "_typescript.applyRenameFile"
      ]
    },
    "hoverProvider": true,
    "renameProvider": true,
    "referencesProvider": true,
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ",",
        "<"
      ]
    },
    "workspaceSymbolProvider": true,
    "implementationProvider": true,
    "typeDefinitionProvider": true,
    "foldingRangeProvider": true
  }
}
extension.ts:92 TypeScript server initialized {capabilities: {…}}
extension.ts:71 TypeScript server: [lspserver] hover {
  "textDocument": {
    "uri": "file:///var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts"
  },
  "position": {
    "line": 23,
    "character": 13
  }
} /var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts
extension.ts:71 TypeScript server: [tsclient] request {
  "command": "quickinfo",
  "seq": 2,
  "type": "request",
  "arguments": {
    "file": "/var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts",
    "line": 24,
    "offset": 14
  }
}
extension.ts:71 TypeScript server: [lspserver] hover {
  "textDocument": {
    "uri": "file:///var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts"
  },
  "position": {
    "line": 23,
    "character": 13
  }
} /var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts
extension.ts:71 TypeScript server: [tsclient] request {
  "command": "quickinfo",
  "seq": 3,
  "type": "request",
  "arguments": {
    "file": "/var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts",
    "line": 24,
    "offset": 14
  }
}
extension.ts:71 TypeScript server: [lspserver] hover {
  "textDocument": {
    "uri": "file:///var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts"
  },
  "position": {
    "line": 23,
    "character": 13
  }
} /var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts
extension.ts:71 TypeScript server: [tsclient] request {
  "command": "quickinfo",
  "seq": 4,
  "type": "request",
  "arguments": {
    "file": "/var/folders/tx/b4v8qh4n467cw8_7f18gj1tc0000gn/T/github.com_sourcegraph_javascript-typescript-langserver_archive_7607b8ab81c0a1f642bbb3ade468987c44c0a0af.zip_23e73b90-e239-11e8-b488-5b9329b51087/repo/src/logging.ts",
    "line": 24,
    "offset": 14
  }
}
extension.ts:71 TypeScript server: [tsclient] processMessage {
  "seq": 0,
  "type": "response",
  "command": "configure",
  "request_seq": 1,
  "success": true
}
extension.ts:71 TypeScript server: [tsclient] request completed {
  "request_seq": 1,
  "success": true
}
extension.ts:71 TypeScript server: [tsclient] processMessage {
  "seq": 0,
  "type": "response",
  "command": "quickinfo",
  "request_seq": 2,
  "success": false,
  "message": "Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:117318:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119683:84)\n    at ProjectService.ensureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119678:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122419:87)\n    at IOSession.Session.getFileAndProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122404:29)\n    at IOSession.Session.getQuickInfoWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122478:31)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:121581:61)\n    at /Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:88\n    at IOSession.Session.executeWithRequestId (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123048:28)\n    at IOSession.Session.executeCommand (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:33)\n    at IOSession.Session.onMessage (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123077:35)\n    at Interface.<anonymous> (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:124340:27)\n    at Interface.emit (events.js:182:13)\n    at Interface._onLine (readline.js:300:10)\n    at Interface._normalWrite (readline.js:443:12)\n    at Socket.ondata (readline.js:159:10)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)"
}
extension.ts:71 TypeScript server: [tsclient] request completed {
  "request_seq": 2,
  "success": false
}
extension.ts:71 TypeScript server: [tsclient] processMessage {
  "seq": 0,
  "type": "response",
  "command": "quickinfo",
  "request_seq": 3,
  "success": false,
  "message": "Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:117318:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119683:84)\n    at ProjectService.ensureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119678:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122419:87)\n    at IOSession.Session.getFileAndProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122404:29)\n    at IOSession.Session.getQuickInfoWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122478:31)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:121581:61)\n    at /Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:88\n    at IOSession.Session.executeWithRequestId (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123048:28)\n    at IOSession.Session.executeCommand (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:33)\n    at IOSession.Session.onMessage (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123077:35)\n    at Interface.<anonymous> (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:124340:27)\n    at Interface.emit (events.js:182:13)\n    at Interface._onLine (readline.js:300:10)\n    at Interface._normalWrite (readline.js:443:12)\n    at Socket.ondata (readline.js:159:10)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)"
}
extension.ts:71 TypeScript server: [tsclient] request completed {
  "request_seq": 3,
  "success": false
}
extension.ts:71 TypeScript server: [tsclient] processMessage {
  "seq": 0,
  "type": "response",
  "command": "quickinfo",
  "request_seq": 4,
  "success": false,
  "message": "Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:117318:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119683:84)\n    at ProjectService.ensureDefaultProjectForFile (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:119678:75)\n    at IOSession.Session.getFileAndProjectWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122419:87)\n    at IOSession.Session.getFileAndProject (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122404:29)\n    at IOSession.Session.getQuickInfoWorker (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:122478:31)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:121581:61)\n    at /Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:88\n    at IOSession.Session.executeWithRequestId (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123048:28)\n    at IOSession.Session.executeCommand (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123057:33)\n    at IOSession.Session.onMessage (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:123077:35)\n    at Interface.<anonymous> (/Users/felix/src/github.com/sourcegraph/ext-lang-typescript/node_modules/typescript/lib/tsserver.js:124340:27)\n    at Interface.emit (events.js:182:13)\n    at Interface._onLine (readline.js:300:10)\n    at Interface._normalWrite (readline.js:443:12)\n    at Socket.ondata (readline.js:159:10)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)"
}
extension.ts:71 TypeScript server: [tsclient] request completed {
  "request_seq": 4,
  "success": false
}
extension.ts:71 TypeScript server: [tsclient] processMessage {
  "seq": 0,
  "type": "event",
  "event": "typingsInstallerPid",
  "body": {
    "pid": 21212
  }
}
extension.ts:71 TypeScript server: [lspserver] Ignored event {
  "event": "typingsInstallerPid"
}
```

The `rootUri`/`rootPath` are pointing to an extracted zip of https://github.com/sourcegraph/javascript-typescript-langserver from GitHub.

If I swap out the language server with https://github.com/sourcegraph/javascript-typescript-langserver it returns hovers correctly.

Any idea what is happening?

**Comment by svenefftinge** [comment]
I cannot reproduce it.
If you start a gitpod workspace through
 - https://gitpod.io/#https://github.com/theia-ide/typescript-language-server

Hovers seem to work fine.

**Comment by felixfbecker** [comment]
Here's a minimal reproduction case: https://github.com/felixfbecker/ts-langserver-repro

**Comment by simark** [comment]
> Here's a minimal reproduction case: https://github.com/felixfbecker/ts-langserver-repro

Note for others who want to try it, it doesn't work with node 8 (`pathToFileURL is not a function`), but it does with node 10.

**Comment by felixfbecker** [comment]
Just added a note about Node 11 being required.

**Comment by felixfbecker** [comment]
Ha, I noticed that it does work if I first send a `textDocument/didOpen` for the file: https://github.com/felixfbecker/ts-langserver-repro/tree/didopen

The LSP spec however states:

> Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed.

https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen

**Comment by rchl** [comment]
I'd say that a hover request, as the name implies, is quite tightly coupled to user hovering something so it kinda makes sense that it only works with document opened.

In theory the server could support it but is not required to do so.

Also see https://github.com/microsoft/language-server-protocol/issues/177#issuecomment-278299653
