### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by bobdobbs** [typescript-language-server/typescript-language-server#898]
I've installed  typescript-language-server on ubuntu linux, using the command `npm i -g typescript-language-server`.
I'm using npm version 6.14.18, and node version 8.15.1.

It installs to '/home/bob/.nvm/versions/node/v8.15.1/bin/typescript-language-server'.

When I run 'typescript-language-server' from the commandline, I get: 

```
/home/bob/.nvm/versions/node/v8.15.1/lib/node_modules/typescript-language-server/lib/cli.mjs:2
import fs$l, { promises, statSync, existsSync, readFileSync as readFileSync$1 } from 'node:fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

```

**Comment by rchl** [comment]
Node 18 is the minimum requirement.
