### ISSUE TITLE
Error while running typescript-language-server --stdio on wsl

### ISSUE THREAD

**Issue by vimulatus** [typescript-language-server/typescript-language-server#915]
I installed typescript-language-server with `npm install -g typescript-language-server`.

When I run `typescript-language-server --stdio`, I get the following error:

```
file:///mnt/c/Users/91978/AppData/Roaming/npm/node_modules/typescript-language-server/lib/cli.mjs:790
    enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by vimulatus** [comment]
nvm, for some reason, my node's version was set to v12. It's working fine after upgrading it. Closing the issue
